# Description 

Cette règle détecte les modifications non autorisées dans la configuration du pare-feu Windows, ce qui peut indiquer une tentative d'altération des contrôles de sécurité du système.

# Criticité : **HIGH**

# Outils

Sysmon

# Règle SPL

```
index=connectix source="*WinEventLog*" EventCode=4947
| eval severity="High"
| eval event_title="Modification des règles de pare-feu"
```

# Règle SIGMA

```
title: Modification des paramètres de pare-feu Windows
logsource:
  product: windows
  service: security
detection:
  selection:
    EventID: 4947
  condition: selection
level: high
description: Détecte les modifications non autorisées dans la configuration du pare-feu Windows.
```

# Explication

Cette règle détecte les modifications des paramètres du pare-feu Windows en recherchant l'EventID 4947 dans les journaux de sécurité. Des changements dans les règles du pare-feu peuvent indiquer une tentative de contournement des contrôles de sécurité.